### ISSUE TITLE
typo in setup.py?

### ISSUE THREAD

**Issue by doomedramen** [TeamMacLean/opimage#2]
install_requires=[
          'numpy',
          'scipy',
          'scikit-image',
          'matplotlib',
          'datetutil' <- should this be dateutil ?
      ],

**Comment by danmaclean** [comment]
yes. This would only cause a problem when it tries to install dependencies. Good spot.

**Comment by doomedramen** [comment]
fixed by https://github.com/TeamMacLean/opimage/commit/bc8340f6f09e4c378dea89e2b926487d98b6743b
